import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Album Art Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Album Art Generator</h1>
        <hr />
        {children}
      </body>
    </html>
  );
}
